### ISSUE TITLE
The project cannot be downloaded. The Credentials.swift file is missing

### ISSUE THREAD

**Issue by Buliceli** [watson-developer-cloud/simple-chat-swift#1]
Download the project to run the Credentials.swift file is missing is that Credentials.swift is a project run red error <unknown> download error: no such project: 0: file or directory:'/Users/lidongdong/Downloads/simple-chat-swift-master/ simple-chat/Simple Chat/Credentials.swift'
Command, /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc, failed, with, exit, code, 1

**Comment by nfriedly** [comment]
That's by design. You must provide your own credentials to be able to run the project. See https://github.com/watson-developer-cloud/simple-chat-swift#credentials
